
version: '{build}.0.0-dev'
configuration: Release
os: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true

environment:
  nuget_apiKey:
    secure: jfcUvHZhgnUboplqTBDWr8mG5PIlrgBv5TA2fhhop4ZSiDxskyy+RtYyeHoduJFR
  myget_apiKey:
    secure: AguzfXNvHBkkDebTyWHK7o9OC5YL3eszT6u7PnzGq2G7ozdUypDlGGpcFsTRYHEc

# Override the 'version' if this is a GH-tag-commit -or- this is a custom branch (i.e not 'master').
init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq $TRUE -and $env:APPVEYOR_REPO_BRANCH -eq 'master')
      { 
          Write-Host " !! Commit is Tagged and branch is 'master' - forcing build version to tag-value." -ForegroundColor Red; 
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/f5b40256fc2ca77d49f1c7773d28406152544c1e/appveyor-build-info.ps'))


before_build:
  # Display .NET Core version
  - cmd: dotnet --info
  # Display minimal restore text
  - cmd: dotnet restore --verbosity quiet

build_script:
  - dotnet build -c %CONFIGURATION% -v minimal /p:Version=%APPVEYOR_BUILD_VERSION% --no-restore

test_script:
  - dotnet test tests\Yahoo.Yui.Compressor.Tests -c %CONFIGURATION% -v minimal --no-restore --no-build
  - dotnet pack -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION% --no-restore --no-build

artifacts:
  - path: '**\*.nupkg'
    name: packaged-nugets
    type: NuGetPackage

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/pk-development/api/v2/package
    api_key:
      secure: AguzfXNvHBkkDebTyWHK7o9OC5YL3eszT6u7PnzGq2G7ozdUypDlGGpcFsTRYHEc
    skip_symbols: true
    artifact: packaged-nugets
    on:
      appveyor_repo_tag: false
  - provider: NuGet
    api_key:
      secure: jfcUvHZhgnUboplqTBDWr8mG5PIlrgBv5TA2fhhop4ZSiDxskyy+RtYyeHoduJFR
    skip_symbols: true
    artifact: packaged-nugets
    on:
      branch: master
      appveyor_repo_tag: true

cache:
  - packages -> **\packages.config