
version: '{build}.0.0-dev'
image: Ubuntu
pull_requests:
  do_not_increment_build_number: true

# Override the 'version' if this is a GH-tag-commit -or- this is a custom branch (i.e not 'master').
init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq $TRUE -and $env:APPVEYOR_REPO_BRANCH -eq 'master')
      { 
          Write-Host " !! Commit is Tagged and branch is 'master' - forcing build version to tag-value." -ForegroundColor Red; 
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/f5b40256fc2ca77d49f1c7773d28406152544c1e/appveyor-build-info.ps'))


matrix:
  fast_finish: true

configuration:
  - Debug
  - Release

install:
  # For RavenDb Testdriver
  - curl -sSL https://dot.net/v1/dotnet-install.sh | sudo bash /dev/stdin --version 3.1.403 --install-dir /usr/share/dotnet
  
  # For .NET50
  - curl -sSL https://dot.net/v1/dotnet-install.sh | sudo bash /dev/stdin --channel 5.0 --version 5.0.100 --install-dir /usr/share/dotnet

before_build:
  # Display .NET Core version
  - dotnet --info

build_script:
  - dotnet restore --verbosity quiet
  - ps: dotnet build -c $env:CONFIGURATION -v minimal /p:Version=$env:APPVEYOR_BUILD_VERSION --no-restore

test_script:
  - ps: |
      if ($env:CONFIGURATION -eq 'Debug')
      {
          dotnet test -c $env:CONFIGURATION -v minimal --no-build --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory './CodeCoverageResults'
      }
      else
      {
          dotnet test -c $env:CONFIGURATION -v minimal --no-build
      }


# We only:
#   - Send DEBUG results up to codecov.
#   - Pack for RELEASE only.
after_test:
  - ps: |
      if ($env:CONFIGURATION -eq 'Debug')
      {
          # Currently, the bash script version is better than the .exe version.
          Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
          bash codecov.sh -s './CodeCoverageResults/' -f '*.xml' -Z
      }
      
      if ($env:CONFIGURATION -eq 'Release')
      {
          dotnet pack -c $env:CONFIGURATION --no-build /p:Version=$env:APPVEYOR_BUILD_VERSION /p:ContinuousIntegrationBuild=true src/WorldDomination.SimpleRavenDb/WorldDomination.SimpleRavenDb.csproj
      }

artifacts:
  - path: '**\*.nupkg'
    name: nuget-packages
    type: NuGetPackage
  - path: '**\*.snupkg'
    name: nuget-symbols
    type: NuGetPackage

deploy:
  - provider: NuGet
    api_key:
      secure: 8EdmbIQFKJXCePp1LFPdA0QoocIaXmLeJeU3LNbvrQ5iROs9hBdKu+3n+94ndxj1
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
